### ISSUE TITLE
Unreadable fonts on websites

### ISSUE THREAD

**Issue by Griszou** [yoursdearboy/omegat-browser#4]
Hi all,

I am using the deepl plugin on a mac and the font is unreadable.

All ideas or help is greatly appreciated.

Best

**Comment by yoursdearboy** [comment]
Hi Griszou,

I have this issue too on my Mac (don't know whether it happens with Linux or Windows too).
The root of the problem is custom font used on their website. I've tried to fix this and looks like the fix works, but not always. You may try to enable/disable the script few times to make it works. Another option to try is to install "Roboto" fonts to your OS. They can be downloaded [here](https://fonts.google.com/specimen/Roboto?selection.family=Roboto).

Tell me if it works for you.

Also, if somebody experiences the same issue on Windows or Linux, please write here about this.

If someone wants to fix this, here is the technical info about the issue:
Looks like that the font isn't loaded by JavaFX web browser or rendered wrong.
I've tried to reset fonts using CSS, but it doesn't work, at least not always. See code of [`resetFonts`](https://github.com/yoursdearboy/omegat-browser/blob/b6b7cec5f0b104151757b4868059416981b804aa/src/main/java/com/yoursdearboy/omegat/plugins/browser/ScriptHelpers.java#L58).

**Comment by Griszou** [comment]
Hey yoursdearboy,

Thanks for your great input. Installing the Roboto fonts did the trick and it's working like a charm.

**Comment by yoursdearboy** [comment]
Version 1.3 fixes fonts reset, now Deepl and LingvoLive should work fine and use the system `sans-serif` fonts.
