### ISSUE TITLE
DeepL Browser Script - Internet connection issue

### ISSUE THREAD

**Issue by Stephan30** [yoursdearboy/omegat-browser#6]
Hello all,
since one month or so I got a strange problem with the DeepL browser script. Whenever I try to translate something in OmegaT with DeepL there pops up the following notification "Es scheint ein Problem mit der Internetverbindung zu geben. Die Funktionalität des DeepL Übersetzers könnte eingeschränkt sein." what translates to English more less like "There seems to be a problem with the Internet connection. The functionality of the DeepL translator may be limited.". Never experienced any troubles with the script before, but now I can't get it working again. Even stranger is, at least to me, that I can navigate in the browser window on the DeepL site and the connection seems to be working just fine (e.g. I can click on the menu button, navigate to the blog, FAQ and so on). But every time I jump from one segment of the source text to the next the entered text won't translate - even manual text input gets me nowhere - only this notification about an issue with my connection comes up again and again. On any internet browser it works fine. I tried also with different wifi and lan connections in different places (e.g. home, my parents, office...) without any changes. The OmegaT version I use is 4.1.5 with Java integrated on Kubuntu 18.04 and OmegaT-Browser 1.2.
Any ideas on this strange behaviour would be more than appreciated :-)

**Comment by Stephan30** [comment]
Maybe if it helps...

33949: FINER: File '/home/stephan/.omegat/browser-scripts/deepl.groovy' added 
33949: Fehler: Uncatched exception in thread [JavaFX Application Thread] 
33949: Fehler: java.lang.NullPointerException 
33949: Fehler:  at com.yoursdearboy.omegat.plugins.browser.ScriptHelpers$1.run(ScriptHelpers.java:62) 
33949: Fehler:  at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295) 
33949: Fehler:  at java.security.AccessController.doPrivileged(Native Method) 
33949: Fehler:  at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294) 
33949: Fehler:  at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) 
33949: Fehler:  at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) 
33949: Fehler:  at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139) 
33949: Fehler:  at java.lang.Thread.run(Thread.java:748)

**Comment by Stephan30** [comment]
Uncommenting the line "ScriptHelpers.resetFonts(pane.getBrowser().getWebEngine())" got rid of the issues indicated above, but the problem still persists...
Maybe DeepL.com changed something on their side to avoid using scripts like this? Nobody else got this problem?
Some response would very much appreciated. Cheers

**Comment by yoursdearboy** [comment]
Hi @Stephan30. The problem was because of CORS (Cross-origin Resource Sharing). Fixed in https://github.com/yoursdearboy/omegat-browser/commit/57231d274ebae84db9b853ad18fb3c2ba76b09f4.
Please, install the new 1.3 version 🙂

Also, the new version fixes unreadable fonts issue #4.

Thank you for the input.

**Comment by Stephan30** [comment]
Fantastic, it all works again :smiley: 

Thank you so very much!

**Comment by GamesGamble** [comment]
The Problem seems to be back. When I enter "In dieser Kategorie sind alle News zu finden." and want to translate it in english it should output something like "In this Category are all news to be found." but it doesnt say anything and then this red popup opens with "Es scheint ein Problem mit der Internetverbindung zu geben. Die Funktionalität des DeepL Übersetzers könnte eingeschränkt sein. (0-T)". My Internet is fine and then i installed the Desktop Client and the same Error appears.
